# Generated by Django 5.2.1 on 2025-06-03 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Informante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('relacao_domicilio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Religiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('endereco', models.CharField(max_length=255)),
                ('especie', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('vila_condominio', 'Casa de vila ou condomínio'), ('cortico', 'Cortiço'), ('inacabado', 'Estrutura degradada/inacabada'), ('asilo', 'Asilo ou instituição'), ('hotel', 'Hotel ou pensão'), ('alojamento', 'Alojamento'), ('outros', 'Outros')], max_length=30)),
                ('agua', models.CharField(max_length=100)),
                ('energia', models.CharField(max_length=100)),
                ('internet', models.BooleanField()),
                ('maquina_lavar', models.BooleanField()),
                ('coleta_lixo', models.CharField(blank=True, max_length=255, null=True)),
                ('comodos', models.IntegerField()),
                ('dormitorios', models.IntegerField()),
                ('banheiros_com_chuveiro', models.IntegerField(blank=True, null=True)),
                ('banheiros_sem_chuveiro', models.IntegerField()),
                ('condicao_ocupacao', models.CharField(choices=[('ainda_pagando', 'Ainda pagando'), ('alugado', 'Alugado'), ('empregador', 'Por empregador'), ('familiar', 'Por familiar'), ('outra', 'Outra forma'), ('pago', 'Já pago, herdado ou ganho')], max_length=30)),
                ('principais_demandas', models.TextField()),
                ('informante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='censoApp.informante')),
                ('religiao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='censoApp.religiao')),
                ('rua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='censoApp.rua')),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=15)),
                ('data_nascimento', models.DateField()),
                ('parentesco', models.CharField(choices=[('responsavel', 'Pessoa responsável pelo domicílio'), ('conjuge_dif', 'Cônjuge ou companheiro(a) de sexo diferente'), ('conjuge_mesmo', 'Cônjuge ou companheiro(a) do mesmo sexo'), ('filho_comum', 'Filho(a) do responsável e do cônjuge'), ('filho_resp', 'Filho(a) somente do responsável'), ('genro_nora', 'Genro ou nora'), ('pai_mae', 'Pai, mãe, padrasto ou madrasta'), ('sogro', 'Sogro(a)'), ('neto', 'Neto(a)'), ('enteado', 'Enteado(a)'), ('irmao', 'Irmão ou irmã'), ('avo', 'Avô ou avó'), ('outro', 'Outro parente'), ('agregado', 'Agregado(a)'), ('bisneto', 'Bisneto(a)'), ('pensionista', 'Pensionista'), ('empregado_dom', 'Empregado(a) doméstico(a)'), ('parente_empregado', 'Parente do(a) empregado(a) doméstico(a)'), ('individual', 'Individual em domicílio coletivo')], max_length=30)),
                ('registro_nascimento', models.CharField(choices=[('cartorio', 'Do cartório'), ('indigena', 'Registro administrativo indígena'), ('nao_tem', 'Não tem'), ('nao_sabe', 'Não sabe')], max_length=20)),
                ('tem_conjuge', models.BooleanField()),
                ('nome_conjuge', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_uniao', models.CharField(blank=True, max_length=100, null=True)),
                ('sabe_ler', models.BooleanField()),
                ('frequenta_escola', models.CharField(max_length=30)),
                ('curso_frequenta', models.CharField(max_length=100)),
                ('concluiu_superior', models.BooleanField()),
                ('possui_deficiencia', models.TextField(blank=True, null=True)),
                ('diagnostico_autismo', models.BooleanField()),
                ('trabalha', models.BooleanField()),
                ('faixa_renda', models.CharField(max_length=50)),
                ('contato', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='censoApp.contato')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censoApp.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Falecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('idade', models.IntegerField()),
                ('tempo_conclusao', models.CharField(max_length=100)),
                ('morador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='censoApp.morador')),
            ],
        ),
        migrations.CreateModel(
            name='Deslocamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_trabalho', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('retorna_casa', models.BooleanField()),
                ('tempo_horas', models.IntegerField()),
                ('tempo_minutos', models.IntegerField()),
                ('meio_transporte', models.CharField(max_length=100)),
                ('morador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='censoApp.morador')),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacao', models.CharField(max_length=100)),
                ('atividade', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('empresa_registrada', models.BooleanField()),
                ('infraestrutura', models.TextField()),
                ('deslocamento', models.BooleanField()),
                ('dificuldades', models.TextField()),
                ('rendimento_suficiente', models.BooleanField()),
                ('interesse_cursos', models.BooleanField()),
                ('trabalho_sazonal', models.BooleanField()),
                ('familia_envovida', models.BooleanField()),
                ('destino_produto', models.CharField(max_length=100)),
                ('acesso_credito', models.BooleanField()),
                ('associacoes', models.TextField()),
                ('sustentabilidade', models.TextField()),
                ('impacto_ambiental', models.TextField()),
                ('expansao_futura', models.BooleanField()),
                ('integracao_comunidade', models.BooleanField()),
                ('melhorias_sugeridas', models.TextField()),
                ('morador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='censoApp.morador')),
            ],
        ),
    ]
