# Generated by Django 5.2.1 on 2025-05-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('subdistrito', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('tipo_domicilio', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Outro', 'Outro')], max_length=20)),
                ('tipo_construcao', models.CharField(choices=[('Alvenaria', 'Alvenaria'), ('Madeira', 'Madeira'), ('Mista', 'Mista'), ('Outro', 'Outro')], max_length=20)),
                ('abastecimento_agua', models.CharField(choices=[('Rede Geral', 'Rede Geral'), ('Poço', 'Poço'), ('Nascente', 'Nascente'), ('Outro', 'Outro')], max_length=20)),
                ('destino_lixo', models.CharField(choices=[('Coleta', 'Coleta'), ('Queima', 'Queima'), ('Enterra', 'Enterra'), ('Outro', 'Outro')], max_length=20)),
                ('numero_banheiros', models.IntegerField()),
                ('esgoto', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10)),
                ('data_nascimento', models.DateField()),
                ('parentesco', models.CharField(choices=[('Responsável', 'Responsável'), ('Cônjuge', 'Cônjuge'), ('Filho', 'Filho'), ('Outro', 'Outro')], max_length=20)),
                ('cor_raca', models.CharField(choices=[('Branca', 'Branca'), ('Preta', 'Preta'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena'), ('Outro', 'Outro')], max_length=20)),
                ('fala_portugues', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3)),
                ('considera_indigena', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3)),
                ('considera_quilombola', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3)),
                ('etnia1', models.CharField(blank=True, max_length=100, null=True)),
                ('etnia2', models.CharField(blank=True, max_length=100, null=True)),
                ('fala_lingua_indigena', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3)),
                ('lingua1', models.CharField(blank=True, max_length=100, null=True)),
                ('lingua2', models.CharField(blank=True, max_length=100, null=True)),
                ('lingua3', models.CharField(blank=True, max_length=100, null=True)),
                ('sabe_ler_escrever', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Mortalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10)),
                ('idade_anos', models.IntegerField()),
                ('idade_meses', models.IntegerField()),
                ('data_falecimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PrestadorInformacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quem_prestou', models.CharField(max_length=100)),
                ('nome_outro_morador', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('faixa', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
    ]
