# Generated by Django 5.2.2 on 2025-06-06 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='informante',
            field=models.OneToOneField(blank=True, choices=[('responsavel', 'Responsável pelo domicílio'), ('conjuge', 'Cônjuge ou companheiro(a)'), ('filho', 'Filho(a) do responsável'), ('outro', 'Outro parente ou agregado')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='censoApp.informante'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='religiao',
            field=models.ForeignKey(blank=True, choices=[('catolica', 'Católica'), ('evangelica', 'Evangélica'), ('espirita', 'Espírita'), ('umbanda', 'Umbanda'), ('candomble', 'Candomblé'), ('islamica', 'Islâmica'), ('budista', 'Budista'), ('judaica', 'Judaica'), ('hindu', 'Hindu'), ('ateu', 'Ateu'), ('agnostico', 'Agnóstico'), ('outra', 'Outra religião')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='censoApp.religiao'),
        ),
        migrations.AlterField(
            model_name='informante',
            name='nome',
            field=models.CharField(choices=[('responsavel', 'Responsável pelo domicílio'), ('conjuge', 'Cônjuge ou companheiro(a)'), ('filho', 'Filho(a) do responsável'), ('outro', 'Outro parente ou agregado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='morador',
            name='contato',
            field=models.OneToOneField(blank=True, choices=[('telefone', 'Telefone'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('outro', 'Outro meio de contato')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='censoApp.contato'),
        ),
        migrations.AlterField(
            model_name='religiao',
            name='descricao',
            field=models.CharField(choices=[('catolica', 'Católica'), ('evangelica', 'Evangélica'), ('espirita', 'Espírita'), ('umbanda', 'Umbanda'), ('candomble', 'Candomblé'), ('islamica', 'Islâmica'), ('budista', 'Budista'), ('judaica', 'Judaica'), ('hindu', 'Hindu'), ('ateu', 'Ateu'), ('agnostico', 'Agnóstico'), ('outra', 'Outra religião')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rua',
            name='nome',
            field=models.CharField(choices=[('asfalto', 'Asfalto'), ('paralelepipedo', 'Paralelepípedo'), ('terra', 'Terra'), ('outro', 'Outro tipo de rua')], max_length=100),
        ),
    ]
