# Generated by Django 5.2.2 on 2025-06-06 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censoApp', '0002_alter_domicilio_informante_alter_domicilio_religiao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='informante',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='religiao',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='contato',
        ),
        migrations.AddField(
            model_name='religiao',
            name='Morador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='censoApp.morador'),
            preserve_default=False,
        ),
    ]
